import { Vehicle, SharedTour, Destination, CustomerReview, FAQItem, Enquiry } from "./types";

export const VEHICLES_DATA: Vehicle[] = [
  {
    id: "v-thar-4x4",
    name: "Mahindra Thar LX 4x4 Hard Top",
    category: "car",
    type: "SUV",
    tagline: "The ultimate 4x4 all-terrain conqueror for Meghalaya & Arunachal mountain passes.",
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
    ],
    seatingCapacity: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    rentalPricePerDay: 4500,
    securityDeposit: 10000,
    minDurationDays: 2,
    pickupDropLocations: ["Guwahati Airport (GAU)", "Guwahati Railway Station", "Shillong City Center"],
    inclusions: [
      "24/7 Roadside Assistance in Assam & Meghalaya",
      "Comprehensive Zero-Dep Commercial Insurance",
      "State Permit for Meghalaya & Assam",
      "Cleaned & Sanitized Vehicle with Full Tank Option",
    ],
    exclusions: [
      "Fuel costs during trip",
      "Inter-state border toll taxes & parking fees",
      "Inner Line Permit (ILP) fees for Arunachal Pradesh",
      "Driver allowance (if self-drive selected)",
    ],
    requiredDocuments: [
      "Original Driving License (valid for 3+ years)",
      "Aadhaar Card or Passport (Original required for verification)",
      "Local reference contact number",
      "Security Deposit in Cash / UPI / Card",
    ],
    rentalRules: [
      "Maximum speed limit 80 km/h tracked via GPS",
      "Off-roading in riverbeds strictly prohibited",
      "Overnight driving after 10 PM on ghat roads discouraged for safety",
    ],
    cancellationPolicyTiers: [
      { daysBefore: 7, refundPercent: 100, description: "Full refund up to 7 days before pickup date" },
      { daysBefore: 3, refundPercent: 50, description: "50% refund for cancellation 3-7 days prior" },
      { daysBefore: 1, refundPercent: 0, description: "No refund within 48 hours of pickup date" },
    ],
    isFeatured: true,
    totalUnits: 6,
    bookedUnits: 5,
    mileageLimit: "Unlimited kms within Assam & Meghalaya",
    engineCC: "2184 cc mHawk",
  },
  {
    id: "v-himalayan-450",
    name: "Royal Enfield Himalayan 450",
    category: "bike",
    type: "Adventure",
    tagline: "Purpose-built dual-sport adventure bike crafted for high-altitude passes of Tawang & Sikkim.",
    images: [
      "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80",
    ],
    seatingCapacity: 2,
    transmission: "Manual",
    fuelType: "Petrol",
    rentalPricePerDay: 1800,
    securityDeposit: 5000,
    minDurationDays: 3,
    pickupDropLocations: ["Guwahati Hub", "Shillong Bike Depot", "Siliguri Office"],
    inclusions: [
      "Dual Helmets (Rider + Pillion)",
      "Rear luggage carrier & pannier stays",
      "Basic tool kit & spare clutch wire",
      "Full insurance coverage",
    ],
    exclusions: ["Fuel", "Pannier boxes (available @ ₹200/day extra)", "Riding gear (Jacket/Boots/Gloves optional)"],
    requiredDocuments: [
      "Valid Two-Wheeler Driving License",
      "Government Photo ID Proof",
      "Security Deposit ₹5,000",
    ],
    rentalRules: ["Rider must be at least 21 years old", "Helmet mandatory for both rider and pillion at all times"],
    cancellationPolicyTiers: [
      { daysBefore: 7, refundPercent: 100, description: "100% refund prior to 7 days" },
      { daysBefore: 2, refundPercent: 50, description: "50% refund within 2-7 days" },
    ],
    isFeatured: true,
    totalUnits: 8,
    bookedUnits: 6,
    mileageLimit: "Unlimited kms",
    engineCC: "452 cc Sherpa",
  },
  {
    id: "v-fortuner-4x4",
    name: "Toyota Fortuner 4x4 Automatic",
    category: "car",
    type: "SUV",
    tagline: "Luxury 7-seater SUV for VIP family tours across luxury resorts and tough mountain terrains.",
    images: [
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541348263662-e082662d82da?auto=format&fit=crop&w=1200&q=80",
    ],
    seatingCapacity: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    rentalPricePerDay: 7500,
    securityDeposit: 15000,
    minDurationDays: 2,
    pickupDropLocations: ["Guwahati Airport VIP Gate", "Guwahati City"],
    inclusions: ["Chauffeur driven option", "Luxury interior sanitization", "All India Permit"],
    exclusions: ["Fuel", "Tolls & Driver overnight charges"],
    requiredDocuments: ["DL with 5+ years experience", "Passport/Aadhaar"],
    rentalRules: ["Security deposit mandatory", "No smoking inside luxury vehicle"],
    cancellationPolicyTiers: [
      { daysBefore: 5, refundPercent: 100, description: "Full refund 5 days in advance" },
      { daysBefore: 2, refundPercent: 50, description: "50% refund 48h prior" },
    ],
    isFeatured: true,
    totalUnits: 4,
    bookedUnits: 1,
    mileageLimit: "300 kms/day included (extra @ ₹18/km)",
    engineCC: "2755 cc Diesel",
  },
  {
    id: "v-re-hunter-350",
    name: "Royal Enfield Hunter 350",
    category: "bike",
    type: "Cruiser",
    tagline: "Agile, lightweight roadster perfect for city cruising and Meghalaya hairpin curves.",
    images: [
      "https://images.unsplash.com/photo-1609630875171-b1321377ee65?auto=format&fit=crop&w=1200&q=80",
    ],
    seatingCapacity: 2,
    transmission: "Manual",
    fuelType: "Petrol",
    rentalPricePerDay: 1200,
    securityDeposit: 3000,
    minDurationDays: 1,
    pickupDropLocations: ["Guwahati Railway Station Hub", "Shillong Center"],
    inclusions: ["2 Helmets", "Third Party Insurance", "Disc Lock"],
    exclusions: ["Fuel"],
    requiredDocuments: ["Valid Indian Motorcycle DL", "Aadhaar Card"],
    rentalRules: ["Speed limit 70 km/h"],
    cancellationPolicyTiers: [
      { daysBefore: 3, refundPercent: 100, description: "Full refund 3 days prior" },
    ],
    isFeatured: false,
    totalUnits: 10,
    bookedUnits: 3,
    mileageLimit: "Unlimited kms",
    engineCC: "349 cc J-Series",
  },
  {
    id: "v-jimny-4x4",
    name: "Maruti Suzuki Jimny Alpha 4x4",
    category: "car",
    type: "SUV",
    tagline: "Compact 4WD legend. Effortless maneuvering through narrow Cherrapunji mountain trails.",
    images: [
      "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80",
    ],
    seatingCapacity: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    rentalPricePerDay: 3800,
    securityDeposit: 8000,
    minDurationDays: 2,
    pickupDropLocations: ["Guwahati Airport", "Guwahati City Hub"],
    inclusions: ["ALL-GRIP PRO 4x4", "Bluetooth Touchscreen", "GPS Tracker"],
    exclusions: ["Fuel", "State Entry Permits"],
    requiredDocuments: ["DL", "Aadhaar / Voter ID"],
    rentalRules: ["GPS monitored vehicle"],
    cancellationPolicyTiers: [
      { daysBefore: 7, refundPercent: 100, description: "100% refund 7 days before" },
    ],
    isFeatured: true,
    totalUnits: 5,
    bookedUnits: 4,
    mileageLimit: "Unlimited kms",
    engineCC: "1462 cc Petrol",
  },
  {
    id: "v-traveller-13",
    name: "Force Traveller 13-Seater Deluxe AC",
    category: "car",
    type: "Tempo Traveller",
    tagline: "Spacious group carrier with pushback seats and high roof for family expeditions.",
    images: [
      "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80",
    ],
    seatingCapacity: 13,
    transmission: "Manual",
    fuelType: "Diesel",
    rentalPricePerDay: 6200,
    securityDeposit: 10000,
    minDurationDays: 3,
    pickupDropLocations: ["Guwahati Airport", "Guwahati Station", "Silchar"],
    inclusions: ["Experienced Driver Included", "Reclining Pushback Seats", "Roof Luggage Carrier"],
    exclusions: ["Tolls & Driver Batta (₹500/night)", "Fuel"],
    requiredDocuments: ["Booking ID", "Lead Passenger Govt ID"],
    rentalRules: ["Driven by company certified driver only"],
    cancellationPolicyTiers: [
      { daysBefore: 7, refundPercent: 100, description: "100% refund 7 days before" },
    ],
    isFeatured: true,
    totalUnits: 6,
    bookedUnits: 6, // Fully Booked example!
    mileageLimit: "250 kms/day baseline",
    engineCC: "2596 cc Diesel",
  },
  {
    id: "v-ktm-adv-390",
    name: "KTM Adventure 390",
    category: "bike",
    type: "Adventure",
    tagline: "High performance tourer with cornering ABS and traction control for thrilling rides.",
    images: [
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80",
    ],
    seatingCapacity: 2,
    transmission: "Manual",
    fuelType: "Petrol",
    rentalPricePerDay: 2200,
    securityDeposit: 7000,
    minDurationDays: 2,
    pickupDropLocations: ["Guwahati Hub", "Shillong Depot"],
    inclusions: ["TFT Screen with Navigation", "Dual Channel Cornering ABS", "Dual Helmets"],
    exclusions: ["Fuel"],
    requiredDocuments: ["DL with 2+ years experience", "Aadhaar Card"],
    rentalRules: ["Gear mandatory"],
    cancellationPolicyTiers: [
      { daysBefore: 5, refundPercent: 100, description: "100% refund 5 days prior" },
    ],
    isFeatured: false,
    totalUnits: 5,
    bookedUnits: 2,
    mileageLimit: "Unlimited kms",
    engineCC: "373 cc Liquid Cooled",
  },
  {
    id: "v-creta-sx",
    name: "Hyundai Creta SX Petrol",
    category: "car",
    type: "Hatchback",
    tagline: "Smooth, comfortable urban crossover for highway cruising from Guwahati to Kaziranga.",
    images: [
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
    ],
    seatingCapacity: 5,
    transmission: "Manual",
    fuelType: "Petrol",
    rentalPricePerDay: 3200,
    securityDeposit: 6000,
    minDurationDays: 1,
    pickupDropLocations: ["Guwahati Airport", "Guwahati City"],
    inclusions: ["Panoramiic Sunroof model", "Clean interior", "Insurance"],
    exclusions: ["Fuel", "State Taxes"],
    requiredDocuments: ["DL", "Aadhaar"],
    rentalRules: ["City and highway usage only"],
    cancellationPolicyTiers: [
      { daysBefore: 3, refundPercent: 100, description: "100% refund 3 days prior" },
    ],
    isFeatured: false,
    totalUnits: 8,
    bookedUnits: 3,
    mileageLimit: "Unlimited kms",
    engineCC: "1497 cc",
  },
];

export const SHARED_TOURS_DATA: SharedTour[] = [
  // ================= 4x4 CAR / SUV GROUP TRIPS =================
  {
    id: "t-tawang-thar-4x4",
    title: "7D Tawang & Sela Pass 4x4 Thar Convoy Expedition",
    slug: "tawang-sela-pass-4x4-thar-convoy",
    destinationId: "d-arunachal",
    destinationName: "Arunachal Pradesh",
    tripFormat: "car",
    vehicleProvided: "Mahindra Thar 4x4 / Fortuner",
    route: "Guwahati → Kaziranga → Dirang → Sela Pass (13,700 ft) → Tawang → Bum La Pass → Guwahati",
    durationDays: 7,
    durationNights: 6,
    startDates: ["2026-09-10", "2026-09-20", "2026-10-05", "2026-10-18"],
    pricePerPerson: 22999,
    totalSeats: 12,
    seatsBooked: 9, // Only 3 seats left
    heroImage: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    ],
    shortHighlights: [
      "4x4 Convoy drive crossing snow-clad Sela Pass at 13,700 ft with support lead vehicle",
      "High-altitude off-roading to Madhuri Lake & Bum La Indo-China border",
      "Visit 400-year-old Tawang Monastery & Kaziranga Rhino Safari",
      "All Inner Line Permits (ILP), fuel, boutique mountain stays & meals included",
    ],
    itinerary: [
      {
        day: 1,
        title: "Guwahati Pickup & Convoy Briefing to Kaziranga",
        description: "Arrive at Guwahati Depot. Convoy briefing, 4x4 vehicle allocation, radio check. Scenic highway convoy to Kaziranga tea valley.",
        distance: "220 km / 5 hrs",
        accommodation: "Iora Retreat, Kaziranga",
        meals: "Dinner Included",
      },
      {
        day: 2,
        title: "Kaziranga Safari & Ascent to Dirang Valley",
        description: "Early morning Kaziranga Jeep Safari. Drive 4x4 convoy into Arunachal foothills towards Dirang Valley.",
        distance: "190 km / 6 hrs",
        accommodation: "Hotel Pemaling, Dirang",
        meals: "Breakfast & Dinner",
      },
      {
        day: 3,
        title: "Sela Pass (13,700 ft) Snow Crossing to Tawang",
        description: "Conquer Sela Pass hairpin loops and frozen Sela Lake. War memorial salute at Jaswant Garh.",
        distance: "140 km / 6 hrs",
        accommodation: "Hotel Tawang Heights",
        meals: "Breakfast & Dinner",
      },
      {
        day: 4,
        title: "Bum La Pass (15,200 ft) & Madhuri Lake Off-Road",
        description: "Full day high-altitude 4x4 expedition to Indo-China border and crystal Madhuri Lake.",
        distance: "80 km off-road trail",
        accommodation: "Hotel Tawang Heights",
        meals: "Breakfast & Dinner",
      },
      {
        day: 5,
        title: "Tawang Monastery & Downhill to Bomdila",
        description: "Visit majestic Tawang Monastery at sunrise. Convoy drive to Bomdila apple orchards.",
        distance: "170 km / 6 hrs",
        accommodation: "Hotel Elysium, Bomdila",
        meals: "Breakfast & Dinner",
      },
      {
        day: 6,
        title: "Bomdila to Bhalukpong River Valley",
        description: "Descend along Kameng River gorge. Evening riverside bonfire with group.",
        distance: "100 km / 4 hrs",
        accommodation: "Prashanti Cottage, Bhalukpong",
        meals: "Breakfast, BBQ & Dinner",
      },
      {
        day: 7,
        title: "Return Convoy to Guwahati Airport",
        description: "Drive back to Guwahati. Airport drop by 4 PM for departing flights.",
        distance: "210 km / 5 hrs",
        meals: "Breakfast Included",
      },
    ],
    inclusions: [
      "Mahindra Thar 4x4 / Fortuner vehicle in convoy with backup support lead",
      "Handpicked 3-star boutique hotels & resorts on twin sharing",
      "Daily Breakfast & Dinner throughout expedition",
      "Inner Line Permit (ILP) documentation & military border clearances",
      "Kaziranga Jeep safari tickets & entry passes",
      "Trip Marshall & certified mountain lead guide",
    ],
    exclusions: ["Airfare to/from Guwahati", "Personal snacks & beverages", "GST 5%"],
    pickupDropPoints: ["Guwahati Airport (GAU) - 10:00 AM", "Guwahati Railway Station - 09:00 AM"],
    accommodationDetails: "Premium eco-resorts & mountain heritage hotels with heated rooms.",
    importantNotes: ["ILP requires Govt ID proof + Passport photo submitted 5 days in advance."],
    cancellationPolicy: [
      { daysBefore: 30, refundPercent: 100, description: "100% refund before 30 days" },
      { daysBefore: 15, refundPercent: 50, description: "50% refund 15-29 days prior" },
    ],
    faqs: [
      {
        id: "faq-thar-1",
        category: "tour",
        question: "Can I self-drive the Thar 4x4 in the convoy?",
        answer: "Yes! You can choose to drive the Thar 4x4 yourself within our guided convoy, or relax as a passenger with our dedicated convoy driver.",
      },
    ],
    isFeatured: true,
  },
  {
    id: "t-meghalaya-4x4",
    title: "5D Meghalaya Off-Road & Living Root Bridge 4x4 Circuit",
    slug: "meghalaya-offroad-living-root-bridge-4x4",
    destinationId: "d-meghalaya",
    destinationName: "Meghalaya",
    tripFormat: "car",
    vehicleProvided: "Mahindra Thar 4x4 / Scorpio-N",
    route: "Guwahati → Shillong → Cherrapunji → Nongriat → Mawlynnong → Dawki → Guwahati",
    durationDays: 5,
    durationNights: 4,
    startDates: ["2026-09-05", "2026-09-18", "2026-10-02", "2026-10-16"],
    pricePerPerson: 17999,
    totalSeats: 12,
    seatsBooked: 10,
    heroImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    ],
    shortHighlights: [
      "4x4 off-road trails through misty Khasi hills and hidden canyon viewpoints",
      "Trek to UNESCO Double Decker Living Root Bridge in Nongriat jungle",
      "Transparent boat ride on crystal Umngot River in Dawki",
      "Cliff jump & swim at turquoise Krang Suri & Phe Phe waterfalls",
    ],
    itinerary: [
      {
        day: 1,
        title: "Guwahati to Shillong Pine Ridges",
        description: "Meet convoy at Guwahati Airport. Drive along Umiam Lake to Shillong. Evening café hopping in Laitumkhrah.",
        distance: "100 km / 3 hrs",
        accommodation: "Hotel Sapphire / Similar, Shillong",
        meals: "Dinner Included",
      },
      {
        day: 2,
        title: "Laitlum Canyons & Cherrapunji Waterfalls",
        description: "Drive to edge of Laitlum Grand Canyon. Continue to Nohkalikai Falls and Mawsmai limestone caves in Sohra.",
        distance: "80 km / 3.5 hrs",
        accommodation: "Cherrapunji Holiday Resort",
        meals: "Breakfast & Dinner",
      },
      {
        day: 3,
        title: "Double Decker Living Root Bridge Expedition",
        description: "Jungle trek down to UNESCO living root bridge bio-structure and Rainbow Falls natural pool.",
        distance: "15 km trek",
        accommodation: "Cherrapunji Holiday Resort",
        meals: "Breakfast & Dinner",
      },
      {
        day: 4,
        title: "Dawki Crystal Waters & Krang Suri Blue Falls",
        description: "Drive to Dawki border river for boating. Swim at stunning Krang Suri waterfalls.",
        distance: "110 km / 4 hrs",
        accommodation: "Riverside Luxury Camp, Dawki",
        meals: "Breakfast, BBQ & Dinner",
      },
      {
        day: 5,
        title: "Return Convoy to Guwahati Airport",
        description: "Morning departure back to Guwahati. Airport drop by 3 PM.",
        distance: "130 km / 4 hrs",
        meals: "Breakfast Included",
      },
    ],
    inclusions: [
      "4x4 SUV vehicle in convoy with fuel & lead guide",
      "3-star stays & riverside glamping tents",
      "Daily Breakfast, Dinner & BBQ night",
      "All entry fees, forest permits & boat ride in Dawki",
    ],
    exclusions: ["Airfare", "Personal snacks"],
    pickupDropPoints: ["Guwahati Airport (GAU)", "Guwahati Railway Station"],
    accommodationDetails: "Handpicked boutique hotels in Shillong & Cherrapunji + Riverside Glamping in Dawki.",
    importantNotes: ["Moderate fitness needed for Nongriat trek."],
    cancellationPolicy: [
      { daysBefore: 15, refundPercent: 100, description: "100% refund before 15 days" },
    ],
    faqs: [],
    isFeatured: true,
  },
  {
    id: "t-sikkim-4x4",
    title: "6D North Sikkim & Gurudongmar 17,800ft 4x4 Expedition",
    slug: "north-sikkim-gurudongmar-4x4-expedition",
    destinationId: "d-sikkim",
    destinationName: "Sikkim",
    tripFormat: "car",
    vehicleProvided: "Mahindra Scorpio 4x4 / Isuzu D-Max",
    route: "Bagdogra/Gangtok → Lachen → Gurudongmar Lake (17,800 ft) → Lachung → Yumthang → Gangtok",
    durationDays: 6,
    durationNights: 5,
    startDates: ["2026-09-12", "2026-09-25", "2026-10-10", "2026-10-24"],
    pricePerPerson: 19500,
    totalSeats: 12,
    seatsBooked: 7,
    heroImage: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
    ],
    shortHighlights: [
      "Conquer high-altitude Tibetan plateau to sacred Gurudongmar Lake at 17,800 ft",
      "Drive through snow-covered Yumthang Valley of Flowers & Zero Point",
      "Experienced mountain marshal lead with oxygen cylinders on board",
      "All restricted area PAP/RAP permits and mountain stays included",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bagdogra / NJP to Gangtok",
        description: "Pickup from Bagdogra. Drive along Teesta River to Gangtok. MG Marg evening stroll.",
        distance: "125 km / 4.5 hrs",
        accommodation: "Hotel Maple Essence, Gangtok",
        meals: "Dinner",
      },
      {
        day: 2,
        title: "Gangtok to Lachen Alpine Village",
        description: "Drive to North Sikkim. View Seven Sister Waterfalls. Overnight in wooden alpine hotel in Lachen.",
        distance: "120 km / 6 hrs",
        accommodation: "Alpine Residency, Lachen",
        meals: "Breakfast, Lunch & Dinner",
      },
      {
        day: 3,
        title: "Gurudongmar Lake (17,800 ft) to Lachung",
        description: "Early morning drive to sacred Gurudongmar Lake near Tibetan border. Marvel at frozen blue waters.",
        distance: "130 km / 7 hrs",
        accommodation: "Lachung Heritage Cottage",
        meals: "Breakfast, Lunch & Dinner",
      },
      {
        day: 4,
        title: "Yumthang Valley & Zero Point to Gangtok",
        description: "Visit Yumthang Valley (Valley of Flowers) and snow-clad Zero Point (15,300 ft). Drive back to Gangtok.",
        distance: "150 km / 6 hrs",
        accommodation: "Hotel Maple Essence, Gangtok",
        meals: "Breakfast & Dinner",
      },
      {
        day: 5,
        title: "Tsomgo Lake & Baba Mandir Excursion",
        description: "High altitude glacial lake excursion and mountain viewpoints.",
        distance: "90 km / 4 hrs",
        accommodation: "Hotel Maple Essence, Gangtok",
        meals: "Breakfast & Dinner",
      },
      {
        day: 6,
        title: "Gangtok Departure to Bagdogra / NJP",
        description: "Drop back to Bagdogra airport by 3 PM.",
        distance: "125 km / 4.5 hrs",
        meals: "Breakfast",
      },
    ],
    inclusions: [
      "4x4 High-Clearance Expedition Vehicle with experienced mountain lead",
      "North Sikkim PAP & RAP Restricted Area Permits",
      "All meals in North Sikkim + Breakfast & Dinner in Gangtok",
      "Oxygen cylinder & emergency medical kit in convoy",
    ],
    exclusions: ["Airfare", "Personal laundry"],
    pickupDropPoints: ["Bagdogra Airport (IXB)", "New Jalpaiguri Railway Station (NJP)"],
    accommodationDetails: "Premium Gangtok hotels + Cozy wooden Himalayan homestays in Lachen & Lachung.",
    importantNotes: ["Passport/Voter ID + 4 photos required for North Sikkim permit."],
    cancellationPolicy: [
      { daysBefore: 15, refundPercent: 100, description: "100% refund before 15 days" },
    ],
    faqs: [],
    isFeatured: true,
  },
  {
    id: "t-kaziranga-majuli-4x4",
    title: "6D Kaziranga Rhino Safari & Majuli Island 4x4 Road Trip",
    slug: "kaziranga-rhino-majuli-4x4-road-trip",
    destinationId: "d-assam",
    destinationName: "Assam",
    tripFormat: "car",
    vehicleProvided: "Toyota Fortuner / Scorpio-N 4x4",
    route: "Guwahati → Kaziranga → Nameri → Majuli River Island → Guwahati",
    durationDays: 6,
    durationNights: 5,
    startDates: ["2026-09-28", "2026-10-18", "2026-11-12"],
    pricePerPerson: 18500,
    totalSeats: 12,
    seatsBooked: 8,
    heroImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    ],
    shortHighlights: [
      "4x4 Convoy drive through Kaziranga tea plantations & Jeep Safari to spot One-Horned Rhinos",
      "Ferry crossing with 4x4 vehicles over Brahmaputra river to Majuli Island",
      "Traditional Mishing tribal village stays & 500-year-old Satra mask makers",
      "Nameri jungle river rafting and eco-camp bonfire night",
    ],
    itinerary: [
      {
        day: 1,
        title: "Guwahati to Kaziranga National Park",
        description: "Convoy starts from Guwahati. Drive through Assam green plains to Kaziranga.",
        distance: "220 km / 5 hrs",
        accommodation: "Iora Retreat, Kaziranga",
        meals: "Dinner Included",
      },
      {
        day: 2,
        title: "Kaziranga Jungle Safari & Tea Trail",
        description: "Morning Jeep Safari in Central range. Afternoon tea garden 4x4 drive.",
        distance: "50 km local",
        accommodation: "Iora Retreat, Kaziranga",
        meals: "Breakfast & Dinner",
      },
      {
        day: 3,
        title: "Kaziranga to Majuli Island Ferry",
        description: "Drive to Nimati Ghat. Ferry crossing across Brahmaputra to Majuli Island.",
        distance: "110 km + 1 hr ferry",
        accommodation: "Prashanti Bamboo Resort, Majuli",
        meals: "Breakfast & Dinner",
      },
      {
        day: 4,
        title: "Majuli Satras & Mishing Tribal Village",
        description: "Explore traditional mask making at Samaguri Satra and Mishing tribal villages.",
        distance: "40 km island trail",
        accommodation: "Prashanti Bamboo Resort, Majuli",
        meals: "Breakfast, Tribal Lunch & Dinner",
      },
      {
        day: 5,
        title: "Majuli to Nameri National Park",
        description: "Morning ferry back. Convoy drive to Nameri forest camp.",
        distance: "140 km / 4 hrs",
        accommodation: "Nameri Eco Camp",
        meals: "Breakfast & Dinner",
      },
      {
        day: 6,
        title: "Nameri Rafting & Guwahati Drop",
        description: "Morning river rafting on Jia Bhoroli river. Drive back to Guwahati airport by 4 PM.",
        distance: "210 km / 4.5 hrs",
        meals: "Breakfast Included",
      },
    ],
    inclusions: [
      "4x4 SUV vehicle in guided convoy with fuel & lead guide",
      "Brahmaputra vehicle ferry tickets",
      "Kaziranga Jeep safari tickets & Nameri river rafting",
      "Boutique resort & bamboo cottage stays with all meals",
    ],
    exclusions: ["Airfare", "Personal beverages"],
    pickupDropPoints: ["Guwahati Airport (GAU)", "Guwahati Railway Station"],
    accommodationDetails: "Eco-resorts in Kaziranga + Stilt bamboo cottages in Majuli.",
    importantNotes: ["Ferry schedules depend on Brahmaputra river condition."],
    cancellationPolicy: [
      { daysBefore: 15, refundPercent: 100, description: "100% refund before 15 days" },
    ],
    faqs: [],
    isFeatured: true,
  },

  // ================= 🏍️ MOTORCYCLE / BIKE GROUP EXPEDITIONS =================
  {
    id: "t-tawang-himalayan-bike",
    title: "7D Tawang High-Altitude Himalayan Motorcycle Expedition",
    slug: "tawang-himalayan-motorcycle-expedition",
    destinationId: "d-arunachal",
    destinationName: "Arunachal Pradesh",
    tripFormat: "bike",
    vehicleProvided: "Royal Enfield Himalayan 450",
    route: "Guwahati → Bhalukpong → Dirang → Sela Pass (13,700 ft) → Tawang → Bum La Pass → Guwahati",
    durationDays: 7,
    durationNights: 6,
    startDates: ["2026-09-15", "2026-10-01", "2026-10-15", "2026-11-01"],
    pricePerPerson: 26500,
    totalSeats: 10,
    seatsBooked: 8, // 2 seats left!
    heroImage: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80",
    ],
    shortHighlights: [
      "Ride Royal Enfield Himalayan 450 across iconic Sela Pass hairpin loops at 13,700 ft",
      "Dedicated backup support vehicle carrying luggage + spare parts + royal mechanic",
      "Lead road captain marshal guiding the entire riding convoy",
      "Inner Line Permits (ILP), mountain riding gear, fuel & premium stays included",
    ],
    itinerary: [
      {
        day: 1,
        title: "Guwahati Bike Handover & Ride to Bhalukpong",
        description: "Meet ride marshal in Guwahati. Bike handover, gear fitment, safety briefing. Ride through Assam tea gardens into Bhalukpong river gates.",
        distance: "210 km / 5.5 hrs ride",
        accommodation: "Prashanti Eco Resort, Bhalukpong",
        meals: "Dinner Included",
      },
      {
        day: 2,
        title: "Bhalukpong to Dirang Valley Mountain Curves",
        description: "Climb through Kameng river gorge. Experience twisting mountain tarmac and mountain viewpoints.",
        distance: "140 km / 5 hrs ride",
        accommodation: "Hotel Pemaling, Dirang",
        meals: "Breakfast & Dinner",
      },
      {
        day: 3,
        title: "Dirang to Tawang over Sela Pass (13,700 ft)",
        description: "The ultimate riding day: conquer Sela Pass high-altitude loops, frozen Sela lake, and Jaswant Garh memorial.",
        distance: "140 km / 6 hrs ride",
        accommodation: "Hotel Tawang Heights",
        meals: "Breakfast & Dinner",
      },
      {
        day: 4,
        title: "Tawang Monastery & Madhuri Lake Mountain Ride",
        description: "Ride to Madhuri Lake and high mountain ridges near Indo-China border.",
        distance: "80 km ride",
        accommodation: "Hotel Tawang Heights",
        meals: "Breakfast & Dinner",
      },
      {
        day: 5,
        title: "Tawang to Bomdila Pine Ridges",
        description: "Downhill mountain ride through apple orchards and scenic passes to Bomdila.",
        distance: "170 km / 6 hrs ride",
        accommodation: "Hotel Elysium, Bomdila",
        meals: "Breakfast & Dinner",
      },
      {
        day: 6,
        title: "Bomdila to Tezpur Plains",
        description: "Ride down to historical town of Tezpur on banks of Brahmaputra River. Farewell riders dinner.",
        distance: "155 km / 5 hrs ride",
        accommodation: "Hotel Kanyapur, Tezpur",
        meals: "Breakfast & Dinner",
      },
      {
        day: 7,
        title: "Tezpur to Guwahati Airport",
        description: "Morning cruise on 4-lane highway back to Guwahati depot. Bike return and airport drop.",
        distance: "180 km / 4 hrs ride",
        meals: "Breakfast Included",
      },
    ],
    inclusions: [
      "Royal Enfield Himalayan 450 motorcycle with crash guards & phone mount",
      "Backup Support Vehicle (Luggage truck with mechanical spares & tools)",
      "Certified RE Master Mechanic & Lead Ride Captain",
      "Handpicked 3-star mountain stays on twin sharing",
      "Daily Breakfast & Dinner throughout ride",
      "Arunachal Pradesh Inner Line Permit (ILP)",
    ],
    exclusions: ["Riding jacket & knee guards (available on rent)", "Airfare", "Fuel during trip"],
    pickupDropPoints: ["Guwahati Airport (GAU)", "Guwahati Railway Station"],
    accommodationDetails: "Cozy mountain view hotels with safe covered bike parking.",
    importantNotes: ["Valid two-wheeler driving license required. Helmets mandatory."],
    cancellationPolicy: [
      { daysBefore: 30, refundPercent: 100, description: "100% refund before 30 days" },
      { daysBefore: 15, refundPercent: 50, description: "50% refund 15-29 days prior" },
    ],
    faqs: [
      {
        id: "faq-bike-1",
        category: "tour",
        question: "Can I bring my own motorcycle on this expedition?",
        answer: "Yes! If you bring your own bike, you get a direct discount of ₹8,000 on the total tour package price.",
      },
    ],
    isFeatured: true,
  },
  {
    id: "t-silkroute-zuluk-bike",
    title: "6D Old Silk Route & Zuluk 32-Loops Motorcycle Tour",
    slug: "silk-route-zuluk-motorcycle-tour",
    destinationId: "d-sikkim",
    destinationName: "Sikkim",
    tripFormat: "bike",
    vehicleProvided: "Royal Enfield Himalayan 450",
    route: "Siliguri → Sillery Gaon → Zuluk (32 Hairpins) → Nathang Valley (13,500 ft) → Gangtok → Siliguri",
    durationDays: 6,
    durationNights: 5,
    startDates: ["2026-09-20", "2026-10-08", "2026-10-22", "2026-11-08"],
    pricePerPerson: 23500,
    totalSeats: 10,
    seatsBooked: 6,
    heroImage: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80",
    ],
    shortHighlights: [
      "Ride the legendary 32 continuous hairpin curves of Zuluk Silk Route",
      "Witness sunrise over Mount Kanchenjunga from Lungthung viewpoint at 13,000 ft",
      "Explore Kupup Elephant Lake, Baba Mandir, and high-altitude Nathang Valley",
      "Full support convoy with luggage van, mechanic, and Sikkim permits included",
    ],
    itinerary: [
      {
        day: 1,
        title: "Siliguri Handover & Ride to Sillery Gaon",
        description: "Bike allocation and briefing in Siliguri. Ride through Teesta river valley into pine village of Sillery Gaon.",
        distance: "95 km / 3.5 hrs ride",
        accommodation: "Sillery Gaon Heritage Homestay",
        meals: "Dinner Included",
      },
      {
        day: 2,
        title: "Sillery Gaon to Zuluk via Rongli Checkpost",
        description: "Permit check at Rongli. Ride into Zuluk mountain hamlet. Sunset over the valley.",
        distance: "80 km / 4 hrs ride",
        accommodation: "Zuluk Wooden Homestay",
        meals: "Breakfast & Dinner",
      },
      {
        day: 3,
        title: "The 32 Hairpins Ride & Nathang Valley (13,500 ft)",
        description: "Ride the iconic 32 zigzag loops of Zuluk. Cross Thambi viewpoint, Lungthung, and stay in Nathang high valley.",
        distance: "60 km / 4 hrs ride",
        accommodation: "Nathang Valley Homestay",
        meals: "Breakfast, Lunch & Dinner",
      },
      {
        day: 4,
        title: "Kupup Elephant Lake to Gangtok",
        description: "Ride past Kupup high lake and Baba Mandir down into Sikkim capital Gangtok.",
        distance: "75 km / 4 hrs ride",
        accommodation: "Hotel Maple Essence, Gangtok",
        meals: "Breakfast & Dinner",
      },
      {
        day: 5,
        title: "Gangtok Scenic Curves & MG Marg Evening",
        description: "Rest & local ride day. Explore Rumtek Monastery and evening on MG Marg.",
        distance: "40 km local",
        accommodation: "Hotel Maple Essence, Gangtok",
        meals: "Breakfast & Dinner",
      },
      {
        day: 6,
        title: "Gangtok to Siliguri Drop",
        description: "Downhill cruise along Teesta River back to Siliguri by 2 PM.",
        distance: "115 km / 4 hrs ride",
        meals: "Breakfast Included",
      },
    ],
    inclusions: [
      "Royal Enfield Himalayan 450 bike with luggage carrier & crash bars",
      "Backup Support Truck with tool kit & spare tires",
      "Lead Road Marshal & local Sikkim mechanic",
      "Silk Route Special Entry Permits & PAP passes",
      "Homestays & 3-star hotel stays with Breakfast & Dinner",
    ],
    exclusions: ["Fuel", "Riding gear", "Airfare"],
    pickupDropPoints: ["Bagdogra Airport (IXB)", "New Jalpaiguri Station (NJP)"],
    accommodationDetails: "Authentic Sikkimese homestays in Zuluk & Nathang + Hotel in Gangtok.",
    importantNotes: ["Voter ID or Passport compulsory for Silk Route Military Checkposts."],
    cancellationPolicy: [
      { daysBefore: 20, refundPercent: 100, description: "100% refund before 20 days" },
    ],
    faqs: [],
    isFeatured: true,
  },
  {
    id: "t-meghalaya-cloud-riders-bike",
    title: "5D Meghalaya Cloud Riders Motorcycle Tour",
    slug: "meghalaya-cloud-riders-motorcycle-tour",
    destinationId: "d-meghalaya",
    destinationName: "Meghalaya",
    tripFormat: "bike",
    vehicleProvided: "RE Scrambler 400X / Himalayan",
    route: "Guwahati → Shillong → Cherrapunji → Dawki → Jowai → Guwahati",
    durationDays: 5,
    durationNights: 4,
    startDates: ["2026-09-08", "2026-09-22", "2026-10-06", "2026-10-20"],
    pricePerPerson: 18500,
    totalSeats: 10,
    seatsBooked: 7,
    heroImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    ],
    shortHighlights: [
      "Ride the smoothest sweeping curves and misty ridges of Khasi & Jaintia hills",
      "Visit living root bridges, transparent Dawki river, and Krang Suri waterfalls",
      "All-inclusive support van, mechanic, fuel support, and riverside tent stay",
    ],
    itinerary: [
      {
        day: 1,
        title: "Guwahati to Shillong Highland Ride",
        description: "Handover in Guwahati. Ride up the 4-lane highway to Shillong. Sunset at Umiam Lake.",
        distance: "100 km / 3 hrs ride",
        accommodation: "Hotel Sapphire, Shillong",
        meals: "Dinner Included",
      },
      {
        day: 2,
        title: "Shillong to Cherrapunji Waterfalls Ride",
        description: "Ride through misty valleys to Nohkalikai and Seven Sisters falls.",
        distance: "80 km / 3 hrs ride",
        accommodation: "Cherrapunji Holiday Resort",
        meals: "Breakfast & Dinner",
      },
      {
        day: 3,
        title: "Nongriat Root Bridge & Ride to Dawki",
        description: "Morning root bridge trek. Afternoon scenic ride to Dawki river camp.",
        distance: "90 km / 3.5 hrs ride",
        accommodation: "Riverside Camp, Dawki",
        meals: "Breakfast, BBQ & Dinner",
      },
      {
        day: 4,
        title: "Krang Suri Blue Falls & Jowai Ridge",
        description: "Swim at Krang Suri waterfall. Ride through Jowai pine hills back to Shillong.",
        distance: "110 km / 4 hrs ride",
        accommodation: "Hotel Sapphire, Shillong",
        meals: "Breakfast & Dinner",
      },
      {
        day: 5,
        title: "Shillong to Guwahati Airport Drop",
        description: "Morning downhill ride back to Guwahati. Bike return by 2 PM.",
        distance: "100 km / 3 hrs ride",
        meals: "Breakfast Included",
      },
    ],
    inclusions: [
      "RE Scrambler 400X or Himalayan 450 motorcycle",
      "Luggage backup vehicle with professional mechanic",
      "Lead rider marshal & route guide",
      "Hotel & riverside glamping stays with Breakfast & Dinner",
    ],
    exclusions: ["Fuel", "Personal gear"],
    pickupDropPoints: ["Guwahati Airport (GAU)", "Guwahati Railway Station"],
    accommodationDetails: "Handpicked hotels + Riverside camping in Dawki.",
    importantNotes: ["Rain riding gear recommended."],
    cancellationPolicy: [
      { daysBefore: 15, refundPercent: 100, description: "100% refund before 15 days" },
    ],
    faqs: [],
    isFeatured: true,
  },
  {
    id: "t-nagaland-dzukou-bike",
    title: "8D Nagaland Hornbill & Dzukou Valley Motorcycle Expedition",
    slug: "nagaland-hornbill-dzukou-motorcycle-expedition",
    destinationId: "d-nagaland",
    destinationName: "Nagaland",
    tripFormat: "bike",
    vehicleProvided: "Royal Enfield Himalayan 450",
    route: "Dimapur → Kohima → Kisama Hornbill Village → Dzukou Valley → Khonoma → Dimapur",
    durationDays: 8,
    durationNights: 7,
    startDates: ["2026-12-01", "2026-12-04", "2026-12-07"],
    pricePerPerson: 28500,
    totalSeats: 10,
    seatsBooked: 9, // 1 seat left
    heroImage: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
    ],
    shortHighlights: [
      "Ride to world-famous Hornbill Festival celebrating 17 Naga tribal warriors",
      "Trek & camp in emerald Dzukou Valley under starlit skies",
      "Ride to Khonoma (Asia's First Green Village) & historical Angami forts",
      "Full motorcycle convoy with mechanic, backup truck, and Nagaland ILP permits",
    ],
    itinerary: [
      {
        day: 1,
        title: "Dimapur Handover & Ride to Kohima",
        description: "Bike handover in Dimapur. Ride up through misty hills to Kohima.",
        distance: "74 km / 3 hrs ride",
        accommodation: "Kohima Heritage Homestay",
        meals: "Dinner Included",
      },
      {
        day: 2,
        title: "Hornbill Festival Ride at Kisama",
        description: "Ride to Kisama village. Witness tribal dances, warrior rituals, and indigenous rock fest.",
        distance: "30 km ride",
        accommodation: "Kohima Heritage Homestay",
        meals: "Breakfast & Dinner",
      },
      {
        day: 3,
        title: "Dzukou Valley Trek & Mountain Camp",
        description: "Park bikes at Viswema base. Trek up into rolling Dzukou Valley for overnight camping.",
        distance: "12 km trek",
        accommodation: "Dzukou Valley Tents",
        meals: "Breakfast, Lunch & Dinner",
      },
      {
        day: 4,
        title: "Dzukou Exploration & Return to Kohima",
        description: "Explore valley caves. Trek back to bikes and ride to Kohima.",
        distance: "10 km trek + 20 km ride",
        accommodation: "Kohima Heritage Homestay",
        meals: "Breakfast & Dinner",
      },
      {
        day: 5,
        title: "Khonoma Green Village Ride",
        description: "Ride to historic green village Khonoma. Traditional Angami lunch and terrace farm walks.",
        distance: "40 km ride",
        accommodation: "Khonoma Homestay",
        meals: "Breakfast & Dinner",
      },
      {
        day: 6,
        title: "Kisama Night Market & Rock Contest",
        description: "Hornbill International Rock Concert and Naga crafts shopping.",
        distance: "30 km ride",
        accommodation: "Kohima Heritage Homestay",
        meals: "Breakfast & Dinner",
      },
      {
        day: 7,
        title: "Tribal Village Discovery Ride",
        description: "Ride to Touphema tourist village and scenic mountain passes.",
        distance: "70 km ride",
        accommodation: "Kohima Heritage Homestay",
        meals: "Breakfast & Dinner",
      },
      {
        day: 8,
        title: "Kohima to Dimapur Airport Drop",
        description: "Ride down to Dimapur. Bike return and airport drop by 12 PM.",
        distance: "74 km / 3 hrs ride",
        meals: "Breakfast Included",
      },
    ],
    inclusions: [
      "Royal Enfield Himalayan 450 bike with luggage carrier",
      "Backup truck with tools, spares & mechanic",
      "Nagaland ILP permit & Hornbill Festival 3-day pass",
      "Homestays & Dzukou camping with Breakfast & Dinner",
    ],
    exclusions: ["Fuel", "Airfare"],
    pickupDropPoints: ["Dimapur Airport (DMU)", "Dimapur Railway Station"],
    accommodationDetails: "Cozy Naga heritage homestays + Tents in Dzukou Valley.",
    importantNotes: ["Nagaland is a dry state."],
    cancellationPolicy: [
      { daysBefore: 30, refundPercent: 100, description: "100% refund before 30 days" },
    ],
    faqs: [],
    isFeatured: true,
  },
];

export const DESTINATIONS_DATA: Destination[] = [
  {
    id: "d-meghalaya",
    name: "Meghalaya",
    slug: "meghalaya",
    stateName: "Meghalaya",
    tagline: "The Abode of Clouds — Waterfalls, Living Root Bridges & Crystal Clear Rivers",
    coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    ],
    overview: "Meghalaya is famous for its misty pine hills, spectacular waterfalls dropping hundreds of feet into deep gorges, centuries-old Living Root Bridges grown by Khasi tribes, and Asia's cleanest village. Ideal for both self-drive road trips and group adventure tours.",
    bestTimeToVisit: "October to April (for crystal clear river water & mild weather) or July to September (for raging monsoon waterfalls).",
    popularPlaces: [
      {
        name: "Cherrapunji (Sohra)",
        description: "Home to Nohkalikai Falls, Mawsmai Cave, and Seven Sisters Waterfalls.",
        image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
      },
      {
        name: "Dawki & Umngot River",
        description: "Transparent river boat riding near the Bangladesh border.",
        image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
      },
      {
        name: "Nongriat Double Decker Root Bridge",
        description: "A 3,500-step jungle trek down to bio-engineered living tree bridges.",
        image: "https://images.unsplash.com/photo-1511884642898-4c92249e20b6?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    suggestedRoutes: [
      {
        name: "Guwahati - Shillong - Sohra - Dawki Circuit",
        duration: "5 to 7 Days",
        description: "The classic Meghalaya loop with smooth highways and picturesque mountain bends.",
      },
    ],
    availableTourIds: ["t-meghalaya-7d"],
    availableVehicleIds: ["v-thar-4x4", "v-himalayan-450", "v-jimny-4x4", "v-re-hunter-350"],
    travelTips: [
      "Always carry a raincoat or light umbrella even in winter months.",
      "Wear sturdy non-slip grip shoes for slippery limestone cave walks and root bridge treks.",
      "BSNL, Jio, and Airtel have good 4G coverage across main towns.",
    ],
    faqs: [
      {
        id: "faq-megh-1",
        category: "general",
        question: "Do tourists need an Inner Line Permit (ILP) for Meghalaya?",
        answer: "No permit is currently required for Indian domestic tourists visiting Meghalaya.",
      },
    ],
  },
  {
    id: "d-assam",
    name: "Assam",
    slug: "assam",
    stateName: "Assam",
    tagline: "Gateway to the Northeast — Wildlife Safaris, Brahmaputra Cruises & Tea Estates",
    coverImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    ],
    overview: "Assam is world-renowned for Kaziranga National Park's One-Horned Rhinoceros population, heritage tea gardens of Jorhat, sacred Kamakhya Temple in Guwahati, and the river island Majuli.",
    bestTimeToVisit: "November to April when national parks remain open for Jeep & Elephant safaris.",
    popularPlaces: [
      {
        name: "Kaziranga National Park",
        description: "UNESCO World Heritage wildlife sanctuary.",
        image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
      },
      {
        name: "Majuli Island",
        description: "World's largest river island and cradle of Assamese Neo-Vaishnavite culture.",
        image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    suggestedRoutes: [
      {
        name: "Guwahati - Kaziranga - Majuli Wildlife & Culture Route",
        duration: "5 Days",
        description: "Smooth NH27 highway drive through scenic Assam tea valleys.",
      },
    ],
    availableTourIds: ["t-majuli-5d", "t-tawang-6d"],
    availableVehicleIds: ["v-fortuner-4x4", "v-creta-sx", "v-traveller-13"],
    travelTips: [
      "Book Kaziranga safari slots at least 15 days in advance during peak winter season.",
    ],
    faqs: [],
  },
  {
    id: "d-arunachal",
    name: "Arunachal Pradesh",
    slug: "arunachal-pradesh",
    stateName: "Arunachal Pradesh",
    tagline: "Land of the Dawn-Lit Mountains — High Passes, Monasteries & Tribal Valleys",
    coverImage: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
    gallery: ["https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80"],
    overview: "India's easternmost frontier state featuring 400-year-old Monpa monasteries in Tawang, snow-capped mountain passes at 13,700 ft, and untouched tribal villages of Ziro Valley.",
    bestTimeToVisit: "March to May (rhododendron blossoms) or October to November (clear blue mountain skies).",
    popularPlaces: [
      {
        name: "Tawang Monastery",
        description: "Largest Buddhist monastery in India perched at 10,000 ft elevation.",
        image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
      },
      {
        name: "Sela Pass",
        description: "High altitude pass at 13,700 ft with pristine lake.",
        image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    suggestedRoutes: [
      {
        name: "Tezpur - Dirang - Tawang High Mountain Highway",
        duration: "6 to 8 Days",
        description: "Challenging mountain route best tackled with 4x4 SUVs or RE Himalayan adventure bikes.",
      },
    ],
    availableTourIds: ["t-tawang-6d", "t-ziro-5d"],
    availableVehicleIds: ["v-thar-4x4", "v-himalayan-450", "v-ktm-adv-390"],
    travelTips: ["Inner Line Permit (ILP) is compulsory for all non-Arunachal residents."],
    faqs: [],
  },
  {
    id: "d-nagaland",
    name: "Nagaland",
    slug: "nagaland",
    stateName: "Nagaland",
    tagline: "Land of Festivals & Warriors — Hornbill Celebration, Dzukou Valley & Naga Culture",
    coverImage: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
    gallery: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80"],
    overview: "Home to 17 distinct Naga tribes with rich cultural heritage, warrior traditions, world-famous Hornbill Festival every December, and emerald Dzukou Valley.",
    bestTimeToVisit: "October to March (December 1-10 for Hornbill Festival).",
    popularPlaces: [
      {
        name: "Kisama Heritage Village",
        description: "The venue for Hornbill Festival near Kohima.",
        image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
      },
      {
        name: "Dzukou Valley",
        description: "Famous trekking destination known for unique dwarf bamboo carpet.",
        image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    suggestedRoutes: [
      {
        name: "Dimapur - Kohima - Khonoma Cultural Trail",
        duration: "5 to 8 Days",
        description: "Winding hill roads connecting historic Naga villages.",
      },
    ],
    availableTourIds: ["t-nagaland-8d"],
    availableVehicleIds: ["v-thar-4x4", "v-himalayan-450"],
    travelTips: ["ILP is mandatory for entry into Nagaland."],
    faqs: [],
  },
  {
    id: "d-sikkim",
    name: "Sikkim",
    slug: "sikkim",
    stateName: "Sikkim",
    tagline: "Jewel of the Himalayas — Alpine Lakes, Glaciers & Kanchenjunga Views",
    coverImage: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
    gallery: ["https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80"],
    overview: "Organic state surrounded by 8,000m Himalayan giants including Mt Kanchenjunga. Pristine glacial lakes at Gurudongmar, hot springs in Yumthang, and historic Silk Route.",
    bestTimeToVisit: "March to May & October to December.",
    popularPlaces: [
      {
        name: "Gurudongmar Lake",
        description: "Sacred high altitude turquoise lake at 17,800 ft.",
        image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    suggestedRoutes: [
      {
        name: "Gangtok - Lachen - Gurudongmar Circuit",
        duration: "6 Days",
        description: "High altitude mountain highway with extreme elevation gain.",
      },
    ],
    availableTourIds: ["t-sikkim-6d"],
    availableVehicleIds: ["v-himalayan-450", "v-thar-4x4"],
    travelTips: ["Protected Area Permit (PAP) required for North Sikkim."],
    faqs: [],
  },
  {
    id: "d-mizoram",
    name: "Mizoram",
    slug: "mizoram",
    stateName: "Mizoram",
    tagline: "Land of Rolling Hills & Blue Mountains — Aizawl Views & Reiek Peak",
    coverImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    overview: "Serene hill country known for warm Mizo hospitality, bamboo dances, scenic ridge town Aizawl, and Tamdil Lake.",
    bestTimeToVisit: "November to March.",
    popularPlaces: [
      {
        name: "Reiek Peak",
        description: "Panoramic cliff offering 360 views of Mizoram hills.",
        image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    suggestedRoutes: [
      {
        name: "Aizawl - Reiek - Tamdil Scenic Drive",
        duration: "4 Days",
        description: "Smooth mountain ridge roads.",
      },
    ],
    availableTourIds: [],
    availableVehicleIds: ["v-re-hunter-350", "v-creta-sx"],
    travelTips: ["ILP required."],
    faqs: [],
  },
  {
    id: "d-tripura",
    name: "Tripura",
    slug: "tripura",
    stateName: "Tripura",
    tagline: "Royal Heritage & Rock Cut Carvings — Ujjayanta Palace & Unakoti",
    coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    overview: "Rich royal history with grand marble palaces in Agartala, floating water palace Neermahal, and ancient rock carvings at Unakoti.",
    bestTimeToVisit: "October to March.",
    popularPlaces: [
      {
        name: "Unakoti Heritage Site",
        description: "Mystical rock carvings of Lord Shiva in dense forest.",
        image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    suggestedRoutes: [
      {
        name: "Agartala - Neermahal - Unakoti Circuit",
        duration: "4 Days",
        description: "State highway network connecting heritage palaces.",
      },
    ],
    availableTourIds: [],
    availableVehicleIds: ["v-creta-sx"],
    travelTips: ["No ILP required for domestic travellers."],
    faqs: [],
  },
  {
    id: "d-manipur",
    name: "Manipur",
    slug: "manipur",
    stateName: "Manipur",
    tagline: "Jewel of India — Floating Loktak Lake & Sangai Deer Sanctuary",
    coverImage: "https://images.unsplash.com/photo-1511884642898-4c92249e20b6?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    overview: "Famous for Loktak Lake with floating phumdis (island masses), Keibul Lamjao National Park (world's only floating park), and vibrant Meitei martial arts.",
    bestTimeToVisit: "November to April.",
    popularPlaces: [
      {
        name: "Loktak Lake & Sendra Island",
        description: "World famous freshwater floating lake ecosystem.",
        image: "https://images.unsplash.com/photo-1511884642898-4c92249e20b6?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    suggestedRoutes: [
      {
        name: "Imphal - Loktak Lake - Moirang Trail",
        duration: "4 Days",
        description: "Valley highway route.",
      },
    ],
    availableTourIds: [],
    availableVehicleIds: ["v-fortuner-4x4"],
    travelTips: ["ILP mandatory."],
    faqs: [],
  },
];

export const CUSTOMER_REVIEWS_DATA: CustomerReview[] = [
  {
    id: "r1",
    author: "Rohan & Priyamvada",
    location: "Mumbai, Maharashtra",
    rating: 5,
    date: "August 2026",
    comment: "Rented the Mahindra Thar 4x4 for 6 days across Cherrapunji and Dawki. Vehicle condition was brand new with flawless 4WD! Majestic Northeast team provided 24/7 WhatsApp support and handled state permits smoothly. 10/10 self-drive experience!",
    itemType: "vehicle",
    itemName: "Mahindra Thar LX 4x4",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    verified: true,
  },
  {
    id: "r2",
    author: "Ananya Sharma",
    location: "Bengaluru, Karnataka",
    rating: 5,
    date: "July 2026",
    comment: "Joined the 7D Meghalaya Shared Group Tour as a solo female traveller. Our tour leader (David) was super knowledgeable and made everyone feel like family. Walking on the Double Decker root bridge was a dream come true!",
    itemType: "tour",
    itemName: "7D Meghalaya Waterfalls & Root Bridges",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    verified: true,
  },
  {
    id: "r3",
    author: "Vikramjit Singh",
    location: "Chandigarh, Punjab",
    rating: 5,
    date: "June 2026",
    comment: "Rented 4 RE Himalayan 450 bikes for our rider gang from Guwahati to Tawang. Bikes were perfectly serviced with pannier racks and fresh tires. Highly transparent security deposit refund within 1 hour of bike drop off!",
    itemType: "vehicle",
    itemName: "Royal Enfield Himalayan 450",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    verified: true,
  },
  {
    id: "r4",
    author: "Siddharth & Friends",
    location: "Delhi NCR",
    rating: 5,
    date: "May 2026",
    comment: "The Tawang 6D shared tour was meticulously planned! Sela Pass snow landscape was magical. Vehicles were comfortable Scorpio 4x4s. All ILP permits were ready before we landed in Guwahati.",
    itemType: "tour",
    itemName: "6D Tawang Monastery & Kaziranga Expedition",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    verified: true,
  },
];

export const GENERAL_FAQS_DATA: FAQItem[] = [
  {
    id: "gfaq-1",
    category: "general",
    question: "What documents are required to rent a car or bike in Northeast India?",
    answer: "You need a valid Indian Driving License (or International Driving Permit for foreign nationals), original Govt Photo ID (Aadhaar or Passport), and a refundable security deposit. For states like Arunachal Pradesh and Nagaland, an Inner Line Permit (ILP) is also required.",
  },
  {
    id: "gfaq-2",
    category: "rental",
    question: "How does the security deposit refund work?",
    answer: "Your security deposit is fully refunded within 1 to 24 hours after the vehicle is returned, inspected for major damage, and verified against traffic violation records.",
  },
  {
    id: "gfaq-3",
    category: "tour",
    question: "What is included in the Shared Tour packages?",
    answer: "All shared tour packages include handpicked hotel/resort/homestay stays on twin sharing basis, daily breakfast and dinner, comfortable SUV/Tempo Traveller transport, experienced local tour leads, permit assistance, and specified entry/activity tickets.",
  },
  {
    id: "gfaq-4",
    category: "general",
    question: "Can I customize a tour or rent a car with a professional mountain driver?",
    answer: "Yes! While our website lists fixed shared tours and self-drive rentals, you can click 'Enquire Now' or 'WhatsApp Us' to request a customized itinerary or add an experienced mountain driver to any rental vehicle.",
  },
  {
    id: "gfaq-5",
    category: "rental",
    question: "What is the cancellation policy for rentals and shared tours?",
    answer: "Rentals cancelled 7 days in advance receive a 100% refund. Shared tours cancelled 30 days prior receive a 100% refund (minus minimal processing fee). Clear cancellation tiers are displayed on every vehicle and tour page.",
  },
];

export const WHY_CHOOSE_US_ITEMS = [
  {
    iconName: "ShieldCheck",
    title: "100% Verified Vehicles & Fleet",
    description: "Every car and motorcycle in our fleet undergoes rigorous 40-point safety checks, zero-dep commercial insurance, and GPS tracking before key handover.",
  },
  {
    iconName: "Compass",
    title: "Local Northeast Experts",
    description: "Born and raised in Guwahati & Shillong, our team knows every mountain curve, secret waterfall trail, and weather window across all 8 states.",
  },
  {
    iconName: "FileCheck2",
    title: "Hassle-Free Permit Handling",
    description: "We handle 100% of your Inner Line Permits (ILP) for Arunachal Pradesh, Nagaland & Mizoram so you focus entirely on the journey.",
  },
  {
    iconName: "BadgeIndianRupee",
    title: "Transparent & Zero Hidden Fees",
    description: "No unexpected toll surprises or mysterious damage charges. Clear security deposit refunds guaranteed within 24 hours of return.",
  },
  {
    iconName: "Headphones",
    title: "24/7 Roadside Assistance",
    description: "Dedicated mountain support team on standby via phone & WhatsApp across Assam, Meghalaya, Sikkim, and Arunachal Pradesh.",
  },
  {
    iconName: "Users",
    title: "Curated Solo & Group Vibes",
    description: "Our shared tours bring together passionate travellers, photographers, and adventurers with experienced local captains.",
  },
];

export const HOW_IT_WORKS_STEPS = {
  cars: [
    {
      step: "01",
      title: "Select 4x4 Expedition Circuit",
      description: "Choose your bucket-list route: Tawang Sela Pass, Meghalaya Off-Road, North Sikkim 17,800ft, or Kaziranga Safari.",
    },
    {
      step: "02",
      title: "Choose Vehicle & Seat Count",
      description: "Book as a self-driving driver in our Thar 4x4 convoy or join as a passenger with our certified convoy driver.",
    },
    {
      step: "03",
      title: "Instant ILP Permits & Briefing",
      description: "Our operations team issues all Inner Line Permits (ILP) and restricted border passes with zero paperwork hassle.",
    },
    {
      step: "04",
      title: "Convoy Rollout with Support Lead",
      description: "Meet your expedition marshal at Guwahati Airport, complete walkie-talkie checks, and roll out with full backup support!",
    },
  ],
  bikes: [
    {
      step: "01",
      title: "Choose Motorcycle Route",
      description: "Pick your riding challenge: Tawang High Passes, Zuluk Silk Route 32 Loops, or Nagaland Hornbill & Dzukou.",
    },
    {
      step: "02",
      title: "Select Royal Enfield Himalayan 450",
      description: "We provide fully equipped Himalayan 450s with crash bars and luggage carriers, or bring your own motorcycle with a fee discount.",
    },
    {
      step: "03",
      title: "Get Riding Gear & Border Clearances",
      description: "Receive riding safety gear, emergency oxygen support, and complete state permits handled by our team.",
    },
    {
      step: "04",
      title: "Ride with Marshal + Backup Mechanic Van",
      description: "Ride freely in formation! Our dedicated luggage truck, spare parts, and master mechanic follow directly behind the convoy.",
    },
  ],
};

export const MOCK_ENQUIRIES_DATA: Enquiry[] = [
  {
    id: "enq-101",
    type: "tour",
    customerName: "Rahul Sharma",
    phone: "+91 98201 44521",
    email: "rahul.sharma88@gmail.com",
    relatedItemName: "7D Tawang & Sela Pass 4x4 Thar Convoy Expedition",
    relatedItemId: "t-tawang-thar-4x4",
    submittedDate: "2026-08-21",
    status: "New",
    message: "We are a group of 3 friends looking to join the 12th September batch. Can we get self-drive Thar?",
    preferredBatch: "2026-09-12",
    numberOfTravellers: 3,
    pickupLocation: "Guwahati Airport (GAU)",
  },
  {
    id: "enq-102",
    type: "rental",
    customerName: "Pooja Deshmukh",
    phone: "+91 97112 33419",
    email: "pooja.d@techcorp.in",
    relatedItemName: "Mahindra Thar LX 4x4 Hard Top",
    relatedItemId: "v-thar-4x4",
    submittedDate: "2026-08-21",
    status: "New",
    message: "Need for a 5-day road trip to Cherrapunji and Dawki. Need rooftop luggage carrier.",
    startDate: "2026-09-05",
    endDate: "2026-09-10",
    pickupLocation: "Guwahati Airport (GAU)",
    dropLocation: "Guwahati Airport (GAU)",
    numberOfTravellers: 2,
  },
  {
    id: "enq-103",
    type: "tour",
    customerName: "Amitabh Banerjee",
    phone: "+91 98310 99882",
    email: "amitabh.banerjee@kolkata.org",
    relatedItemName: "6D Old Silk Route & Zuluk 32-Loops Motorcycle Tour",
    relatedItemId: "t-silkroute-zuluk-bike",
    submittedDate: "2026-08-20",
    status: "Contacted",
    message: "Will be bringing 2 riders. Need helmet and riding jackets on rent. Please share ILP requirement list.",
    preferredBatch: "2026-09-15",
    numberOfTravellers: 2,
    pickupLocation: "Siliguri / NJP Depot",
  },
  {
    id: "enq-104",
    type: "rental",
    customerName: "Dr. Vikram Sethi",
    phone: "+91 94191 22334",
    email: "dr.vsethi@aiims.edu",
    relatedItemName: "Toyota Fortuner 4x4 Legender",
    relatedItemId: "v-fortuner-4x4",
    submittedDate: "2026-08-20",
    status: "Confirmed",
    message: "Family trip with parents to Kaziranga and Shillong. Require professional chauffeur.",
    startDate: "2026-09-18",
    endDate: "2026-09-24",
    pickupLocation: "Guwahati Airport (GAU)",
    dropLocation: "Guwahati Airport (GAU)",
    numberOfTravellers: 5,
  },
  {
    id: "enq-105",
    type: "tour",
    customerName: "Ananya Roy",
    phone: "+91 98745 66778",
    email: "ananya.roy@designstudio.com",
    relatedItemName: "5D Meghalaya Off-Road & Living Root Bridge 4x4 Circuit",
    relatedItemId: "t-meghalaya-4x4",
    submittedDate: "2026-08-19",
    status: "Confirmed",
    message: "Token payment completed. Looking forward to river canyon trek in Mawlyngbna.",
    preferredBatch: "2026-09-08",
    numberOfTravellers: 2,
    pickupLocation: "Guwahati Airport (GAU)",
  },
  {
    id: "enq-106",
    type: "tour",
    customerName: "Siddharth Menon",
    phone: "+91 98450 11223",
    email: "sid.menon@bengaluru.io",
    relatedItemName: "7D Tawang High-Altitude Himalayan Motorcycle Expedition",
    relatedItemId: "t-tawang-himalayan-bike",
    submittedDate: "2026-08-19",
    status: "Contacted",
    message: "Experienced rider. Does the Himalayan 450 come with tubeless cross-spoke wheels?",
    preferredBatch: "2026-09-22",
    numberOfTravellers: 1,
    pickupLocation: "Guwahati Airport (GAU)",
  },
  {
    id: "enq-107",
    type: "rental",
    customerName: "Karan Johar Walia",
    phone: "+91 99100 55443",
    email: "karan.walia@delhiventures.com",
    relatedItemName: "Royal Enfield Himalayan 450",
    relatedItemId: "v-himalayan-450",
    submittedDate: "2026-08-18",
    status: "New",
    message: "Self-ride rental for 8 days from Guwahati to Tawang. Please confirm security deposit return procedure.",
    startDate: "2026-10-02",
    endDate: "2026-10-10",
    pickupLocation: "Guwahati Airport (GAU)",
    dropLocation: "Guwahati Airport (GAU)",
    numberOfTravellers: 2,
  },
  {
    id: "enq-108",
    type: "tour",
    customerName: "Meera Krishnan",
    phone: "+91 94440 88990",
    email: "meera.krishnan@chennai.org",
    relatedItemName: "8D Nagaland Hornbill & Dzukou Valley Motorcycle Expedition",
    relatedItemId: "t-nagaland-dzukou-bike",
    submittedDate: "2026-08-17",
    status: "Cancelled",
    message: "Had to cancel due to office conference reschedule. Will re-book for December Hornbill festival.",
    preferredBatch: "2026-11-28",
    numberOfTravellers: 2,
    pickupLocation: "Dimapur Airport",
  },
  {
    id: "enq-109",
    type: "rental",
    customerName: "Rohan Kapoor",
    phone: "+91 98119 77889",
    email: "rohan.kapoor@gurugram.net",
    relatedItemName: "Mahindra Scorpio-N 4x4 Z8L",
    relatedItemId: "v-scorpio-n",
    submittedDate: "2026-08-17",
    status: "Confirmed",
    message: "Confirmed for family trip to Shillong and Cherrapunji.",
    startDate: "2026-09-14",
    endDate: "2026-09-19",
    pickupLocation: "Guwahati Railway Station",
    dropLocation: "Guwahati Airport (GAU)",
    numberOfTravellers: 4,
  },
  {
    id: "enq-110",
    type: "tour",
    customerName: "Tenzing Norbu",
    phone: "+91 97740 12345",
    email: "tenzing.norbu@himalaya.in",
    relatedItemName: "6D North Sikkim & Gurudongmar 17,800ft 4x4 Expedition",
    relatedItemId: "t-sikkim-4x4",
    submittedDate: "2026-08-16",
    status: "Contacted",
    message: "Want to confirm if medical oxygen cylinders are provided on Gurudongmar pass route.",
    preferredBatch: "2026-09-20",
    numberOfTravellers: 2,
    pickupLocation: "Bagdogra Airport (IXB)",
  },
  {
    id: "enq-111",
    type: "rental",
    customerName: "Sneha Patel",
    phone: "+91 98250 33221",
    email: "sneha.patel@ahmedabad.biz",
    relatedItemName: "Toyota Innova Crysta ZX Luxury",
    relatedItemId: "v-innova-crysta",
    submittedDate: "2026-08-15",
    status: "New",
    message: "Need spacious 7-seater for 4 adults + 2 kids across Meghalaya circuit.",
    startDate: "2026-10-15",
    endDate: "2026-10-21",
    pickupLocation: "Guwahati Airport (GAU)",
    dropLocation: "Guwahati Airport (GAU)",
    numberOfTravellers: 6,
  },
  {
    id: "enq-112",
    type: "tour",
    customerName: "Devendra Singhania",
    phone: "+91 98300 44332",
    email: "dev.singhania@mumbai.co",
    relatedItemName: "6D Kaziranga Rhino Safari & Majuli Island 4x4 Road Trip",
    relatedItemId: "t-kaziranga-majuli-4x4",
    submittedDate: "2026-08-14",
    status: "Confirmed",
    message: "All permits and river ferry tickets confirmed. Excited for Majuli mask-making session.",
    preferredBatch: "2026-10-05",
    numberOfTravellers: 4,
    pickupLocation: "Guwahati Airport (GAU)",
  },
];

